# Generated by Django 2.0.2 on 2018-02-09 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180209_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 2, 9, 13, 37, 15, 369699, tzinfo=utc), verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
