# Generated by Django 2.0.2 on 2018-02-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180210_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfilter',
            name='retweet_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='taskfilter',
            name='filters',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
