# Generated by Django 2.0.2 on 2018-02-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180211_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfilter',
            name='retweet_count',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
